LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_ARM_MODE := arm
LOCAL_MODULE := liblog
LOCAL_SRC_FILES := liblog-prebuilt.a
LOCAL_MODULE_SUFFIX := .a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_ARM_MODE := arm
LOCAL_MODULE := liblog
LOCAL_SRC_FILES := liblog-prebuilt.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := liblog
LOCAL_SRC_FILES := liblog-x86-prebuilt.a
LOCAL_MODULE_SUFFIX := .a
include $(BUILD_HOST_PREBUILT)
